---
output: html_document
editor_options: 
chunk_output_type: inline
---

Loading library
```{r}
packages = c(
  'plyr',
  'dplyr',
  'tidyr',
  'tidyverse',
  'sf',
  'stringr',
  "forcats",
  'transformr',
  'gifski',
  'zoo',
  'png',
  'quantmod',
  'reshape2',
  'scales',
  'highcharter'
)

for (p in packages) {
  if (!require(p, character.only = T)) {
    install.packages(p)
  }
  library(p, character.only = T)
}

```
Remove wind variable and update year up to 1990
```{r}
#------------- Inital Files ------------------
mpsz <- st_read(dsn = "geospatial",
                layer = "MP14_SUBZONE_WEB_PL")
mainDF <- read_csv("merged data/dataset.csv")
mainDF$date <- as.Date(with(mainDF, paste(Year, Month, Day,sep="-")), "%Y-%b-%d")

mainDF <- mainDF %>%
  filter(!str_detect(mainDF$Measurement, "Wind")) %>%
  filter(Year >= 1990) 

saveRDS(mainDF, file = "shiny data/mainDF.RDS")
```
Used by Voilin Plot
```{r}
tmpV <- mainDF %>%
    select(Year, Month, Region, SZ, Measurement, Value) %>%
    mutate(Measurement= str_replace(Measurement, " \\(.*\\)", ""))%>%
    mutate(Month = fct_relevel(Month,
                              "Jan","Feb","Mar",
                              "Apr","May","Jun",
                              "Jul","Aug","Sep",
                              "Oct","Nov","Dec"))
    
saveRDS(tmpV, file = "shiny data/tmpV.RDS")
```

Used by Ridge Plot
```{r}
#-------------- Non Maps -----------------------
tm <- mainDF %>%
    mutate(Month = fct_relevel(Month,
                             "Jan","Feb","Mar",
                             "Apr","May","Jun",
                             "Jul","Aug","Sep",
                             "Oct","Nov","Dec"))

masterDF <- tm %>%
  filter(str_detect(tm$Measurement, "Daily Rainfall Total")) %>%
  group_by(Year,Month,Region,SZ) %>%
  summarise(mean_rain = mean(Value, na.rm = TRUE))

tm_tmp <- tm %>%
  filter(str_detect(tm$Measurement, "Mean Temperature")) %>%
  group_by(Year,Month,Region,SZ) %>%
  summarise(mean_temp = mean(Value, na.rm = TRUE))

masterDF$mean_temp = tm_tmp$mean_temp

masterDF <- masterDF %>%
  mutate_at(vars(mean_temp,
                 mean_rain,),
            funs(round(., 1)))

saveRDS(masterDF, file = "shiny data/masterDF.RDS")
```

Used by Correlation Plot
```{r}
masterDF3 <- tm %>%
  filter(str_detect(tm$Measurement, "Daily Rainfall Total")) %>%
  group_by(Year,Month,Region) %>%
  summarise(mean_rain = mean(Value, na.rm = TRUE))

tm_tmp2 <- tm %>%
  filter(str_detect(tm$Measurement, "Mean Temperature")) %>%
  group_by(Year,Month,Region) %>%
  summarise(mean_temp = mean(Value, na.rm = TRUE))

masterDF3$mean_temp = tm_tmp2$mean_temp

masterDF3 <- masterDF3 %>%
  mutate_at(vars(mean_temp,
                 mean_rain,),
            funs(round(., 1))) %>%
  na.omit()

saveRDS(masterDF3, file = "shiny data/masterDF3.RDS")
```

Used by Choropleth Map
```{r}
#-------------- Maps----------------
masterDF2  <- tm %>%
  filter(str_detect(tm$Measurement, "Daily Rainfall Total")) %>%
  group_by(Year,Month,SZ) %>%
  summarise(mean_rain = mean(Value, na.rm = TRUE))

df2Temp <- tm %>%
  filter(str_detect(tm$Measurement, "Mean Temperature")) %>%
  group_by(Year,Month,SZ) %>%
  summarise(mean_temp = mean(Value, na.rm = TRUE))

masterDF2$mean_temp = df2Temp$mean_temp
masterDF2<- masterDF2 %>%
  mutate_at(vars(mean_temp,mean_rain), funs(round(., 1))) 

saveRDS(masterDF2, file = "shiny data/masterDF2.RDS")
```

Used by Temperature Trends
```{r}
#-------------- Temperature trends------------
Mastertemp <- mainDF %>%
  filter(str_detect(mainDF$Measurement, "Temperature")) %>%
  group_by(Year, Month) %>%
  summarise(median = median(Value, na.rm = TRUE),
            lower = min(Value, na.rm = TRUE),
            upper = max(Value, na.rm = TRUE),
            avg = mean(Value, na.rm =TRUE)) %>%
  na.omit()
Mastertemp$date <- as.Date(with(Mastertemp, paste(Year,Month, "01", sep="-")), "%Y-%b-%d")

smooth_vals <- predict(loess(median~Year,Mastertemp))
Mastertemp$smooth_vals <- smooth_vals

Mastertemp <- Mastertemp %>%
  mutate_at(c(3:6,8), funs(round(., 1)))


x <- c("Max: ", "Median: ", "Min: ", "Predict: ")
y <-
  sprintf("{point.%s}", c("upper", "median", "lower", "smooth_vals"))

tltip <- tooltip_table(x, y)

median_tmp <- mainDF %>%
  filter(str_detect(mainDF$Measurement, "Temperature"))

med <- median(median_tmp$Value, na.rm = TRUE)
low <- min(median_tmp$Value, na.rm = TRUE)
high = max(median_tmp$Value, na.rm = TRUE)

trendChart <- hchart(Mastertemp,
                     type = "columnrange",
                     hcaes(
                       x = date,
                       low = lower,
                       high = upper,
                       color = smooth_vals
                     )) %>%
  hc_yAxis(
    tickPositions = c(low - 5, med, high + 5),
    gridLineColor = "#000000",
    labels = list(format = "{value} C", useHTML = TRUE)
  ) %>%
  hc_add_series(
    data = Mastertemp,
    type = "line",
    hcaes(x = date, y = smooth_vals),
    color = "#B71C1C"
  ) %>%
  hc_tooltip(
    useHTML = TRUE,
    headerFormat = as.character(tags$small("{point.x: %Y %b}")),
    pointFormat = tltip
  )
saveRDS(trendChart, file = "shiny data/trendChart.RDS")
```

Used by Temperature Radials
```{r}
#--------------Weathers Radials------------
Mastertemp2 <- mainDF %>%
  filter(str_detect(mainDF$Measurement, "Temperature")) %>%
  select(Region,Year, date, Value) %>%
  group_by(Year,date,Region) %>%
  summarise(min_temperaturec = min(Value, na.rm = TRUE),
            max_temperaturec = max(Value, na.rm = TRUE),
            mean_temperaturec = mean(Value, na.rm = TRUE),
            median_temperaturec = median(Value, na.rm = TRUE)) %>%
  na.omit()

smooth_vals <- predict(loess(median_temperaturec ~Year,Mastertemp2))
Mastertemp2$smooth_vals <- smooth_vals

Mastertemp2 <- Mastertemp2 %>%
  mutate_at(4:8, funs(round(., 1)))

saveRDS(Mastertemp2, file = "shiny data/Mastertemp2.RDS")

Mastertemp3 <- Mastertemp2 %>%
  group_by(Year, date) %>%
  summarise(
    min_temperaturec = min(min_temperaturec, na.rm = TRUE),
    max_temperaturec = max(max_temperaturec, na.rm = TRUE),
    mean_temperaturec = mean(mean_temperaturec , na.rm = TRUE),
    median_temperaturec = median(median_temperaturec, na.rm = TRUE)
  ) %>%
  na.omit()

smooth_vals <-
  predict(loess(median_temperaturec ~ Year, Mastertemp3))
Mastertemp3$smooth_vals <- smooth_vals

Mastertemp3 <- Mastertemp3 %>%
  mutate_at(3:7, funs(round(., 1)))

saveRDS(Mastertemp3, file = "shiny data/Mastertemp3.RDS")
```

Clendar Heatmap
```{r}
#-------------- Calendar Heatmap ----------------
dat <- mainDF %>%
  select(Year, Month, Day, Measurement, Value) %>%
  filter(str_detect(mainDF$Measurement, "Mean Temperature|Daily Rainfall Total")) %>%
  filter(!is.na(Value))

dat$date <- as.Date(with(dat, paste(Year, Month, Day, sep = "-")), "%Y-%b-%d")

dat$Year <- as.numeric(as.POSIXlt(dat$date)$year + 1900)
dat$Month <- as.numeric(as.POSIXlt(dat$date)$mon + 1)
dat$monthf <-
  factor(
    dat$Month,
    levels = as.character(1:12),
    labels = c(
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ),
    ordered = TRUE
  )
dat$weekday = as.POSIXlt(dat$date)$wday
dat$weekdayf <-
  factor(
    dat$weekday,
    levels = rev(0:6),
    labels = rev(c(
      "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"
    )),
    ordered = TRUE
  )
dat$yearmonth <- as.yearmon(dat$date)
dat$yearmonthf <- factor(dat$yearmonth)
dat$week <- as.numeric(format(dat$date, "%W"))
dat <- ddply(dat, .(yearmonthf), transform, monthweek = 1 + week - min(week))

saveRDS(dat, file = "shiny data/dat.RDS")
```

Gift Creation
```{r}
test2 <- mainDF %>% 
  filter(Measurement == "Mean Temperature (°C)") %>% 
  filter(!is.na(Value))

smooth_vals = predict(loess(Value~Year,test2))
test2$date <- as.Date(test2$date)
test2$smooth_vals <- smooth_vals
#https://stackoverflow.com/questions/60856938/animate-points-and-regression-line-along-date-with-gganimate
anim <- ggplot(test2,aes(date,Value))+
  geom_line(color="red") +
  geom_line(aes(y = smooth_vals), colour = "blue")+
  labs(
    title = "Temperature accross Singapore",
    x="Year",
    y="Temperature (\u00B0C)"
    )+
  transition_reveal(date) + 
  ease_aes("linear")

anim_save("temperature_trend.gif",animate(anim,renderer = gifski_renderer()))
```

```{r}
tmpV <- readRDS("shiny data/tmpV.RDS")
db9_tmp <- tmpV %>%
      select(Year,Month,Region) 

db9_tmp <- db9_tmp  %>%
        filter(Year == as.numeric(2019))

db9_tmp <- db9_tmp %>%
        filter(Month == as.numeric(input$db9m))

db9_tmp <- db9_tmp %>%
        distinct(Region)
```




