---
output: html_document
editor_options: 
  chunk_output_type: inline
---
The purpose of this file is to: \
1. crawl the data from web \
2. combine all csv into one single DF
3. remove all speical characters ("-") to null values
4. Join area code to the main DF for every area
5. create subzone columns by mapping lat and lng columns with MLP shape into our data DF.
5. output one single csv file 

```{r echo = TRUE,eval=FALSE}
packages <-
  c('tidyverse',
  'data.table',
  'sf',
  'tidyr',
  'stringr',
  'lubridate',
  'dplyr',
  'zoo',
  'gganimate',
  'transformr',
  'gifski',
  'png',
  'quantmod',
  'reshape2',
  'plyr',
  'scales')

for (p in packages) {
  if (!require(p, character.only = T)) {
    install.packages(p)
  }
    library(p, character.only = T)
}


```


```{r echo=TRUE, warning=FALSE}
# months = list('01',
#               '02',
#               '03',
#               '04',
#               '05',
#               '06',
#               '07',
#               '08',
#               '09',
#               '10',
#               '11',
#               '12')
# areacode = read_csv("merged data\\AreaID.csv")
# years <- list(1980:2019)
# 
# for (x in 1:nrow(areacode)) {
#   area = areacode[x, 1]
#   for (i in 1:length(years[[1]] - 1)) {
#     year = years[[1]][i]
#     for (month in months) {
#       downloadurl = paste(
#         "http://www.weather.gov.sg/files/dailydata/DAILYDATA_",
#         area,
#         "_",
#         sprintf("%s", year),
#         month,
#         ".csv",
#         sep = ""
#       )
#       temp = paste(".\\raw data\\",
#                    area,
#                    "_",
#                    sprintf("%s", year),
#                    "_",
#                    month,
#                    ".csv",
#                    sep = "")
#       
#       if (!file.exists(file.path(temp))) {
#         skip_to_next <- FALSE
#         tryCatch(
#           download.file(downloadurl, temp),
#           error = function(e) {
#             skip_to_next <<- TRUE
#           }
#         )
#         if (skip_to_next) {
#           next
#         }
#       }
#     }
#   }
# }

```


```{r echo=TRUE, warning=FALSE}
file_location = "merged data\\dataset.csv"

if (file_test("-f", file_location )){
  DT = read_csv(file = file_location)
  print("File Loaded!")
}else{
  area_code_df = read_csv(file = "merged data\\area_geocode.csv")
  area_code_df <- area_code_df %>% mutate_at(vars(Lng), as.numeric)
  
  # load CRS
  mpsz <- st_read(dsn = "geospatial",
                  layer = "MP14_SUBZONE_WEB_PL")
  
  # convert the CRS to lat/lng
  mpsz <- st_transform(mpsz, 4326)
  
  # convert to a simple features object
  map2(area_code_df$Lng, area_code_df$Lat, ~ st_point(c(.x, .y))) %>%
    st_sfc(crs = 4326) %>%
    st_sf(area_code_df[, -(4:5)], .) -> tmp_sf
  
  # which subzone each one belongs in
  area_code_df <- bind_cols(area_code_df,
                            mpsz[as.numeric(st_within(tmp_sf, mpsz)),]) %>%
                            select(ID, Station, Region, Lat, Lng, SZ = SUBZONE_N) %>%
                            mutate(SZ = toupper(SZ))

  setwd("raw data\\")
  files <- list.files(pattern="*.csv")
  DT = do.call(rbind, lapply(files, fread))
  DT = rbindlist(lapply(files, fread))
  
  DT <- DT %>%
         mutate_all(funs(type.convert(as.character(replace(., .=="—", NA))))) %>%
         mutate(Month = month.abb[Month]) %>%
         left_join(area_code_df, by = c("Station")) %>%
         gather(Measurement, Value, 5:13)
  
  # Remove na rows
  DT =  DT[complete.cases(DT[ , 1]),]

  setwd("..\\")
  write_csv(DT,file_location,col_names = TRUE)
  print("File Created!")
}
```

```{r}
mpsz <- st_read(dsn = "geospatial",
                layer = "MP14_SUBZONE_WEB_PL")
mainDF <- read.csv("merged data\\dataset.csv")
mainDF$date <- as.Date(with(mainDF, paste(Year, Month, Day,sep="-")), "%Y-%B-%d")
```

```{r}
Mastertemp2 <- mainDF %>%
  filter(str_detect(mainDF$Measurement, "Temperature")) %>%
  select(Region,Year, date, Value) %>%
  group_by(Year,Region,date) %>%
  summarise(min_temperaturec = min(Value, na.rm = TRUE),
            max_temperaturec = max(Value, na.rm = TRUE),
            mean_temperaturec = mean(Value, na.rm = TRUE),
            median_temperaturec = median(Value, na.rm = TRUE)) %>%
  na.omit()

smooth_vals <- predict(loess(median_temperaturec ~Year,Mastertemp2))
Mastertemp2$smooth_vals <- smooth_vals

Mastertemp2 <- Mastertemp2 %>%
              mutate_at(4:8, funs(round(., 1)))

Mastertemp <- mainDF %>%
  filter(str_detect(mainDF$Measurement, "Temperature")) %>%
  group_by(Year, Month) %>%
  summarise(median = median(Value, na.rm = TRUE),
            lower = min(Value, na.rm = TRUE),
            upper = max(Value, na.rm = TRUE),
            avg = mean(Value, na.rm =TRUE)) %>%
  na.omit()
Mastertemp$date = as.Date(with(Mastertemp, paste(Year,month.abb[Month], "01", sep=" ")), "%Y %b %d")
smooth_vals <- predict(loess(median~Year,Mastertemp))
Mastertemp$smooth_vals <- smooth_vals

Mastertemp <- Mastertemp %>%
  mutate_at(c(3:6,8), funs(round(., 1))) 

```

```{r}
rainfall <- mainDF %>%
  filter(str_detect(mainDF$Measurement, "Daily Rainfall Total")) %>%
  group_by(Year,Month) %>%
  summarise(mean_rain = mean(Value, na.rm = TRUE))

temperature <- mainDF %>%
  filter(str_detect(mainDF$Measurement, "Mean Temperature")) %>%
  group_by(Year,Month) %>%
  summarise(mean_temp = mean(Value, na.rm = TRUE))

masterDF <- rainfall %>%
  mutate(Month = fct_relevel(Month, 
                             "Jan","Feb","Mar",
                             "Apr","May","Jun",
                             "Jul","Aug","Sep",
                             "Oct","Nov","Dec"))
masterDF$mean_temp = temperature$mean_temp
masterDF <- masterDF %>%
  mutate_at(vars(mean_temp,mean_rain), funs(round(., 1))) %>%
  na.omit()
```

```{r}
test2 <- mainDF %>% 
  filter(Measurement == "Mean Temperature (Â°C)") %>% 
  filter(!is.na(Value))

smooth_vals = predict(loess(Value~Year,test2))
test2$date <- as.Date(test2$date)
test2$smooth_vals <- smooth_vals
#https://stackoverflow.com/questions/60856938/animate-points-and-regression-line-along-date-with-gganimate
anim <- ggplot(test2,aes(date,Value))+
  geom_line(color="red") +
  geom_line(aes(y = smooth_vals), colour = "blue")+
  labs(
    title = "Temperature accross Singapore",
    x="Year",
    y="Temperature (\u00B0C)"
    )+
  transition_reveal(date) + 
  ease_aes("linear")

anim_save("temperature_trend.gif",animate(anim,renderer = gifski_renderer()))
```

```{r}
dat <- mainDF %>%
  select(Year, Month, Day, Measurement, Value) %>%
  filter(str_detect(mainDF$Measurement, "Mean Temperature")) %>%
  filter(!is.na(Value))
dat$date <-
  as.Date(with(dat, paste(Year, Month, Day, sep = "-")), "%Y-%b-%d")

dat$Year <- as.numeric(as.POSIXlt(dat$date)$year + 1900)
dat$Month <- as.numeric(as.POSIXlt(dat$date)$mon + 1)
dat$monthf <-
  factor(
    dat$Month,
    levels = as.character(1:12),
    labels = c(
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ),
    ordered = TRUE
  )
dat$weekday = as.POSIXlt(dat$date)$wday
dat$weekdayf <-
  factor(
    dat$weekday,
    levels = rev(0:6),
    labels = rev(c(
      "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"
    )),
    ordered = TRUE
  )
dat$yearmonth <- as.yearmon(dat$date)
dat$yearmonthf <- factor(dat$yearmonth)
dat$week <- as.numeric(format(dat$date, "%W"))
dat <- ddply(dat, .(yearmonthf), transform, monthweek = 1 + week - min(week))

smooth_vals = predict(loess(Value ~ Year, dat))
dat$smooth_vals <- smooth_vals
```




