---
title: "Tanny dashboard"
author: "Tanny Lai"
date: "4 April 2020"
output: html_document
runtime: shiny
---

```{r}
packages = c(
  'dplyr',
  'tidyverse',
  'sf', 
  'tmap',
  'plotly',
  'stringr',
  'shinydashboard',
  'ggstatsplot',
  'gganimate',
  'ggridges',
  "gridExtra"
)

for (p in packages) {
  if (!require(p, character.only = T)) {
    install.packages(p)
  }
  library(p, character.only = T)
}

mainDF <- read.csv("merged data\\dataset.csv")
```

```{r}
rainfall<- mainDF %>%
  filter(str_detect(mainDF$Measurement,"Daily Rainfall Total")) %>%
  select(
    'Region',
    'Station',
    'Year',
    'Month',
    'Day',
    'Value')  %>%
  group_by(Region,Station,Year,Month) %>%
  summarise(mean_rain = mean(Value,na.rm = TRUE),
            total_rain = sum(Value, na.rm = TRUE))%>%
  filter(!is.na(Year)) 

temperature<- mainDF %>%
  filter(str_detect(mainDF$Measurement,"Mean Temperature")) %>%
  select(
    'Region',
    'Station',
    'Year',
    'Month',
    'Day',
    'Value')  %>%
  group_by(Region,Station,Year,Month) %>%
  summarise(mean_temp = mean(Value,na.rm = TRUE))%>%
  filter(!is.na(Year))

rainfall$mean_temp = temperature$mean_temp
```

```{r eruptions, echo=FALSE}
# renderPlot({
# ggstatsplot::ggbetweenstats(
#   data = temperature,
#   x = Month,
#   y = mean_temp,
#   title = "Monthly Temperature",
#   ggtheme = ggthemes::theme_fivethirtyeight(),
#   ggstatsplot.layer = FALSE,
#   messages = FALSE
# ) # further modification outside of ggstatsplot

```


```{r}
fun_mean <- function(x) {
  return(data.frame(y = round(mean(x), 2), label = round(mean(x, na.rm = T), 2)))
}

rain <- ggplot(rainfall, aes(factor(Month), mean_rain))

rain + geom_violin(fill = "lightblue") +
        geom_boxplot(width = 0.1,
               color = "white",
               alpha = 0.2) +  stat_summary(
                 fun = mean,
                 colour = "darkred",
                 geom = "point",
                 shape =
                   18,
                 size = 3,
                 show.legend = FALSE
               ) + stat_summary(
                 fun.data = fun_mean,
                 geom = "text",
                 vjust = -0.9,
                 size = 3.5
               ) + ggtitle ("Rainfall distribution by month") + xlab("Month") + ylab("Average Rainfall ( mm )")
```


```{r}
# mean_r <- aggregate(mean_rain ~ Month, rainfall, mean)
# 
# mean_r <- round(mean_r,2)

fun_mean <- function(x){
  return(data.frame(y=round(mean(x),2),label=round(mean(x,na.rm=T),2)))}

temp <- ggplot(temperature, aes(factor(Month), mean_temp))
temp + geom_violin(fill="lightblue")+
  geom_boxplot(width=0.1, color="white", alpha=0.2)+stat_summary(fun=mean, colour="darkred", geom="point",
                                                                 shape=18, size=3,show.legend = FALSE)+stat_summary(fun.data = fun_mean, geom="text", vjust=-0.9, size=3.5)+
  ggtitle ("Temperature distribution by month") +
  xlab("Month") +  ylab ("Average temperature ( ºC )") +theme_minimal()
```

```{r}
ggstatsplot::ggscatterstats(
  data = rainfall,
  x = mean_rain,
  y = mean_temp,
  xlab = "Mean rainfall distribution",
  ylab = "Mean Temperature",
  title = "Understanding mammalian sleep",
  centrality.parameter = "median",
  messages = FALSE,
  xlim=c(0,30)
)
```

```{r}
temp <- ggplot(temperature, aes(x = mean_temp, y = Month, fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01, gradient_lwd = 1.) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_discrete(expand = expansion(mult = c(0.01, 0.25))) +
  scale_fill_viridis_c(name = "Temp. [C]", option = "B") +
  labs(
    title = 'Temperatures in Lincoln NE',
    subtitle = 'Mean temperatures (Celcius) by month'
  ) +
  theme_ridges(font_size = 13, grid = TRUE) + 
  theme(axis.title.y = element_blank())
tmp <- temperature %>% 
filter(Year == 2018)

temp+xlim(min(tmp$mean_temp, na.rm=TRUE)-1,max(tmp$mean_temp, na.rm=TRUE)+1)
```

```{r}
rf <- ggplot(rainfall, aes(x = mean_rain, y = factor(Month), fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01, gradient_lwd = 1.) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_discrete(expand = expand_scale(mult = c(0.01, 0.25))) +
  scale_fill_viridis_c(name = "Rain Precipitation (mm)", option = "D") +
  labs(
    title = 'Temperatures in Lincoln NE',
    subtitle = 'Mean Rainfall Precipiration (mm) by month'
  ) +
  theme_ridges(font_size = 13, grid = TRUE) + 
  theme(axis.title.y = element_blank())

tmp <- rainfall %>% 
filter(Year == 2018)

rf+xlim(0,max(tmp$mean_rain, na.rm=TRUE)+5)

```

```{r}
scatterPlot <- ggplot(rainfall,aes(x= mean_rain, y= mean_temp, color='#E69F00')) + 
  geom_point() + 
  scale_color_manual(values = c('#999999')) + 
  theme(legend.position=c(0,1), legend.justification=c(0,1))
# scatterPlot

# scatter plot of x and y variables
# color by groups
xdensity <- ggplot(rainfall, aes(x= mean_rain, fill='#E69F00')) + 
  geom_density(alpha=.5) + 
  scale_fill_manual(values = c('#E69F00')) + 
  theme(legend.position = "none")
# xdensity

ydensity <- ggplot(rainfall, aes(y=mean_temp, fill='#E69F00')) + 
  geom_density(alpha=.5) + 
  scale_fill_manual(values = c('#999999','#E69F00')) + 
  theme(legend.position = "none")
# ydensity

blankPlot <- ggplot()+geom_blank(aes(1,1))+
  theme(plot.background = element_blank(), 
   panel.grid.major = element_blank(),
   panel.grid.minor = element_blank(), 
   panel.border = element_blank(),
   panel.background = element_blank(),
   axis.title.x = element_blank(),
   axis.title.y = element_blank(),
   axis.text.x = element_blank(), 
   axis.text.y = element_blank(),
   axis.ticks = element_blank()
     )

grid.arrange(xdensity, blankPlot, scatterPlot, ydensity, 
        ncol=2, nrow=2, widths=c(4, 1.4), heights=c(1.4, 4))
```


