The purpose of this file is to: \
1. crawl the data from web \
2. combine all csv into one single DF
3. remove all speical characters ("-") to null values
4. Join area code to the main DF for every area
5. output one single csv file 

```{r echo = TRUE,eval=FALSE}
packages <-
  c('tidyverse',
  'ggExtra',
  'data.table',
  'MASS',
  'reshape',
  'dplyr',
  'tibble',
  'reshape2')

for (p in packages) {
  if (!require(p, character.only = T)) {
    install.packages(p)
  }
    library(p, character.only = T)
}

```


```{r eval=FALSE, warning=FALSE}
months = list('01',
              '02',
              '03',
              '04',
              '05',
              '06',
              '07',
              '08',
              '09',
              '10',
              '11',
              '12')
              areacode = read_csv("merged data\\AreaID.csv")
              years <- list(1980:2019)

for (x in 1:nrow(areacode)){
  area = areacode[x,1]
  for (i in 1:length(years[[1]]-1)){
    year = years[[1]][i]
    for( month in months){
      downloadurl = paste(
          "http://www.weather.gov.sg/files/dailydata/DAILYDATA_",
          area,
          "_",
          sprintf("%s", year),
          month,
          ".csv",
          sep = ""
        )
      temp = paste(".\\raw data\\",
                   area,
                   "_",
                   sprintf("%s", year),
                   "_",
                   month,
                   ".csv",
                   sep = "")
      
      if (!file.exists(file.path(temp))){
          skip_to_next <- FALSE
          tryCatch(download.file(downloadurl,temp), error = function(e) { skip_to_next <<- TRUE})
          if(skip_to_next) { next }
      } 
    }
  }
}

```


```{r echo=TRUE, warning=FALSE, eval=FALSE}
file_location = "merged data\\dataset.csv"
area_code_file_location = "merged data\\area_geocode.csv"
area_code_df = read_csv(file = area_code_file_location)

if (file_test("-f", file_location )){
  DT = read_csv(file = file_location)
  print("File Loaded!")
}else{
  setwd("raw data\\")
  files <- list.files(pattern="*.csv")
  DT = do.call(rbind, lapply(files, fread))
  DT = rbindlist(lapply(files, fread))

  DT <- DT %>%
         mutate(Date = paste(Day,Month,Year, sep = "-")) %>%
         mutate_all(funs(type.convert(as.character(replace(., .=="—", NA))))) %>%
         left_join(area_code_df, by = c("Station"))
         
  DT <-
    melt(
      DT,
      id = c(
        "Station",
        "Year",
        "Month",
        "Day",
        "Date",
        "ID",
        "Region",
        "Lat. (N)",
        "Long. (E)",
        "Elevation above mean sea-level (m)"
      )
    )
  setwd("..\\")
  
  # Remove na rows
  DT =  DT[complete.cases(DT[ , 12]),]
  write_csv(DT,file_location,col_names = TRUE)
  print("File Created!")
}
```


